name             'gcfdev'
maintainer       'Tom Mitchell'
maintainer_email 'tmitchell@bbn.com'
license          'GENI Public License'
description      'Configures for gcf development'
long_description 'Installs dependencies of gcf for development.'
version          '0.1.0'
